export interface Set {
  completed: boolean,
  created_timestamp: string,
  db_set_id: number,
  event_game_number: number,
  event_id: string,
  game_type: string,
  game_number: number,
  id: number,
  p1_family: string,
  p1_given: string,
  p2_family: string,
  p2_given: string,
  p3_family: string,
  p3_given: string,
  p4_family: string,
  p4_given: string,
  p1_id: string,
  p2_id: string,
  p3_id: string,
  p4_id: string,
  set_id: string,
  team_1_points: string,
  team_2_points: string,
  tournament_id: string,
  winning_team: string
}
